/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 27-nov.-2021 20:24:58 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */




IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Aplicantes_Sede]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Aplicantes] DROP CONSTRAINT [FK_Aplicantes_Sede]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Aplicantes_Cargo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Aplicantes] DROP CONSTRAINT [FK_Aplicantes_Cargo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_AplicantesRequerimiento_Requerimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [AplicantesRequerimiento] DROP CONSTRAINT [FK_AplicantesRequerimiento_Requerimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_AplicantesRequerimiento_Aplicantes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [AplicantesRequerimiento] DROP CONSTRAINT [FK_AplicantesRequerimiento_Aplicantes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Area_Cargo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Area] DROP CONSTRAINT [FK_Area_Cargo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Asistencia_Empleado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Asistencia] DROP CONSTRAINT [FK_Asistencia_Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Cargo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Cargo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Rendimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Rendimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Sede]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Sede]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Evaluación_Aplicantes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Evaluación] DROP CONSTRAINT [FK_Evaluación_Aplicantes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Observacion_Empleado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Observacion] DROP CONSTRAINT [FK_Observacion_Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Remuneraciones_Empleado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Remuneraciones] DROP CONSTRAINT [FK_Remuneraciones_Empleado]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Aplicantes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Aplicantes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[AplicantesRequerimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [AplicantesRequerimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Area]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Asistencia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Asistencia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cargo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cargo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Evaluación]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Evaluación]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Observacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Observacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Remuneraciones]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Remuneraciones]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rendimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rendimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Requerimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Requerimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Sede]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Sede]
GO

/* Create Tables */

CREATE TABLE [Aplicantes]
(
	[Apellido] char(50) NULL,
	[Correo_electronico] char(100) NULL,
	[Direccion] char(100) NULL,
	[Dni] char(10) NULL,
	[Experiencia] char(100) NULL,
	[Grado_instruccion] char(50) NULL,
	[Habilidades] char(50) NULL,
	[Nombre] char(50) NULL,
	[Numero_telefonico] char(10) NULL,
	[Objetivos] char(100) NULL,
	[Pass] char(10) NULL,
	[Titulo] char(100) NULL,
	[AplicantesID] int NOT NULL,
	[SedeID] int NOT NULL,
	[CargoID] int NOT NULL
)
GO

CREATE TABLE [AplicantesRequerimiento]
(
	[RequerimientoID] int NULL,
	[AplicantesID] int NULL
)
GO

CREATE TABLE [Area]
(
	[Nombre_area] char(50) NULL,
	[AreaID] int NOT NULL,
	[CargoID] int NOT NULL
)
GO

CREATE TABLE [Asistencia]
(
	[Descripcion] char(10) NULL,
	[Fecha] date NULL,
	[AsistenciaID] int NOT NULL,
	[EmpleadoID] int NOT NULL
)
GO

CREATE TABLE [Cargo]
(
	[Nombre_cargo] char(100) NULL,
	[CargoID] int NOT NULL
)
GO

CREATE TABLE [Empleado]
(
	[Apellido] char(50) NULL,
	[Correo_electronico] char(100) NULL,
	[Direccion] char(100) NULL,
	[Dni] char(10) NULL,
	[Nombre] char(50) NULL,
	[Numero_telefonico] char(10) NULL,
	[Pass] char(10) NULL,
	[Sueldo] float NULL,
	[EmpleadoID] int NOT NULL,
	[CargoID] int NOT NULL,
	[RendimientoID] int NOT NULL,
	[SedeID] int NOT NULL
)
GO

CREATE TABLE [Evaluación]
(
	[Fechaevaluacion] datetime NULL,
	[Pregunta1] char(3) NULL,
	[Pregunta2] char(3) NULL,
	[Pregunta3] char(3) NULL,
	[Pregunta4] char(3) NULL,
	[Pregunta5] char(3) NULL,
	[Puntajetotal] int NULL,
	[EvaluaciónID] int NOT NULL,
	[AplicantesID] int NOT NULL
)
GO

CREATE TABLE [Observacion]
(
	[Descripcion] char(50) NULL,
	[Fecha] datetime NULL,
	[ObservacionID] int NOT NULL,
	[EmpleadoID] int NOT NULL
)
GO

CREATE TABLE [Remuneraciones]
(
	[Numasistencias] int NULL,
	[Sueldo] float NULL,
	[RemuneracionesID] int NOT NULL,
	[EmpleadoID] int NOT NULL
)
GO

CREATE TABLE [Rendimiento]
(
	[Cant_faltas] int NULL,
	[Cant_horascumplidas] int NULL,
	[Cant_objetivoscumplidos] int NULL,
	[Cant_observaciones] int NULL,
	[Opinion_empleado] char(100) NULL,
	[RendimientoID] int NOT NULL
)
GO

CREATE TABLE [Requerimiento]
(
	[Descripcion] char(100) NULL,
	[RequerimientoID] int NOT NULL
)
GO

CREATE TABLE [Sede]
(
	[Nombre_sede] char(100) NULL,
	[SedeID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Aplicantes] 
 ADD CONSTRAINT [PK_Aplicantes]
	PRIMARY KEY CLUSTERED ([AplicantesID] ASC)
GO

ALTER TABLE [Area] 
 ADD CONSTRAINT [PK_Area]
	PRIMARY KEY CLUSTERED ([AreaID] ASC)
GO

ALTER TABLE [Asistencia] 
 ADD CONSTRAINT [PK_Asistencia]
	PRIMARY KEY CLUSTERED ([AsistenciaID] ASC)
GO

ALTER TABLE [Cargo] 
 ADD CONSTRAINT [PK_Cargo]
	PRIMARY KEY CLUSTERED ([CargoID] ASC)
GO

ALTER TABLE [Empleado] 
 ADD CONSTRAINT [PK_Empleado]
	PRIMARY KEY CLUSTERED ([EmpleadoID] ASC)
GO

ALTER TABLE [Evaluación] 
 ADD CONSTRAINT [PK_Evaluación]
	PRIMARY KEY CLUSTERED ([EvaluaciónID] ASC)
GO

ALTER TABLE [Observacion] 
 ADD CONSTRAINT [PK_Observacion]
	PRIMARY KEY CLUSTERED ([ObservacionID] ASC)
GO

ALTER TABLE [Remuneraciones] 
 ADD CONSTRAINT [PK_Remuneraciones]
	PRIMARY KEY CLUSTERED ([RemuneracionesID] ASC)
GO

ALTER TABLE [Rendimiento] 
 ADD CONSTRAINT [PK_Rendimiento]
	PRIMARY KEY CLUSTERED ([RendimientoID] ASC)
GO

ALTER TABLE [Requerimiento] 
 ADD CONSTRAINT [PK_Requerimiento]
	PRIMARY KEY CLUSTERED ([RequerimientoID] ASC)
GO

ALTER TABLE [Sede] 
 ADD CONSTRAINT [PK_Sede]
	PRIMARY KEY CLUSTERED ([SedeID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Aplicantes] ADD CONSTRAINT [FK_Aplicantes_Sede]
	FOREIGN KEY ([SedeID]) REFERENCES [Sede] ([SedeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Aplicantes] ADD CONSTRAINT [FK_Aplicantes_Cargo]
	FOREIGN KEY ([CargoID]) REFERENCES [Cargo] ([CargoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AplicantesRequerimiento] ADD CONSTRAINT [FK_AplicantesRequerimiento_Requerimiento]
	FOREIGN KEY ([RequerimientoID]) REFERENCES [Requerimiento] ([RequerimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AplicantesRequerimiento] ADD CONSTRAINT [FK_AplicantesRequerimiento_Aplicantes]
	FOREIGN KEY ([AplicantesID]) REFERENCES [Aplicantes] ([AplicantesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Area] ADD CONSTRAINT [FK_Area_Cargo]
	FOREIGN KEY ([CargoID]) REFERENCES [Cargo] ([CargoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Asistencia] ADD CONSTRAINT [FK_Asistencia_Empleado]
	FOREIGN KEY ([EmpleadoID]) REFERENCES [Empleado] ([EmpleadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Cargo]
	FOREIGN KEY ([CargoID]) REFERENCES [Cargo] ([CargoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Rendimiento]
	FOREIGN KEY ([RendimientoID]) REFERENCES [Rendimiento] ([RendimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Sede]
	FOREIGN KEY ([SedeID]) REFERENCES [Sede] ([SedeID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Evaluación] ADD CONSTRAINT [FK_Evaluación_Aplicantes]
	FOREIGN KEY ([AplicantesID]) REFERENCES [Aplicantes] ([AplicantesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Observacion] ADD CONSTRAINT [FK_Observacion_Empleado]
	FOREIGN KEY ([EmpleadoID]) REFERENCES [Empleado] ([EmpleadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Remuneraciones] ADD CONSTRAINT [FK_Remuneraciones_Empleado]
	FOREIGN KEY ([EmpleadoID]) REFERENCES [Empleado] ([EmpleadoID]) ON DELETE No Action ON UPDATE No Action
GO





INSERT INTO SEDE VALUES ('Sede Amazonas','1');
INSERT INTO SEDE VALUES ('Sede Áncash','2');
INSERT INTO SEDE VALUES ('Sede Apurímac','3');
INSERT INTO SEDE VALUES ('Sede Arequipa','4');
INSERT INTO SEDE VALUES ('Sede Trujillo','5');
INSERT INTO SEDE VALUES ('Sede Cajamarca','6');
INSERT INTO SEDE VALUES ('Sede Callao','7');
INSERT INTO SEDE VALUES ('Sede Cusco','8');
INSERT INTO SEDE VALUES ('Sede Huancavelica','9');
INSERT INTO SEDE VALUES ('Sede Huánuco','10');
GO





INSERT INTO CARGO VALUES ('Médico','1');
INSERT INTO CARGO VALUES ('Intercambio','2');
INSERT INTO CARGO VALUES ('Especialistas','3');
INSERT INTO CARGO VALUES ('Personal de enfermería','4');
INSERT INTO CARGO VALUES ('Personal de enfermería práctico','5');
INSERT INTO CARGO VALUES ('asistentes médicos','6');
INSERT INTO CARGO VALUES ('Defensor del paciente','7');
INSERT INTO CARGO VALUES ('Auxiliares de enfermería.','8');
INSERT INTO CARGO VALUES ('Lavanderia','9');
INSERT INTO CARGO VALUES ('Mantenimiento','10');
INSERT INTO CARGO VALUES ('Camaristas','11');
INSERT INTO CARGO VALUES ('Jefe de Area','12');
INSERT INTO CARGO VALUES ('Jefe de Recepción','13');
INSERT INTO CARGO VALUES ('Asistente de Gerencia','14');
INSERT INTO CARGO VALUES ('Jefe de Selección','15');
INSERT INTO CARGO VALUES ('Asistente de Gerencia','16');
INSERT INTO CARGO VALUES ('Recepcionista','17');
INSERT INTO CARGO VALUES ('Jefe de RRHH','18');
GO





INSERT INTO AREA VALUES ('ANESTESIOLOGÍA','1','7');
INSERT INTO AREA VALUES ('CARDIOLOGÍA','2','16');
INSERT INTO AREA VALUES ('CUIDADOS INTENSIVOS','3','1');
INSERT INTO AREA VALUES ('DIGESTIVO','4','14');
INSERT INTO AREA VALUES ('HEMATOLOGÍA','5','6');
INSERT INTO AREA VALUES ('MEDICINA INTERNA','6','2');
INSERT INTO AREA VALUES ('NEFROLOGÍA','7','4');
INSERT INTO AREA VALUES ('NEUMOLOGÍA','8','13');
INSERT INTO AREA VALUES ('ONCOLOGÍA','9','8');
INSERT INTO AREA VALUES ('PEDIATRÍA/NEONATOLOGÍA','10','14');
INSERT INTO AREA VALUES ('REHABILITACIÓN','11','8');
INSERT INTO AREA VALUES ('URGENCIAS','12','11');
INSERT INTO AREA VALUES ('CIRUGÍA GENERAL Y DIGESTIVA','13','14');
INSERT INTO AREA VALUES ('CIRUGÍA ORTOPÉDICA Y TRAUMATOLOGÍA','14','14');
INSERT INTO AREA VALUES ('DERMATOLOGÍA','15','18');
INSERT INTO AREA VALUES ('GINECOLOGÍA Y OBSTETRICIA','16','17');
INSERT INTO AREA VALUES ('OFTALMOLOGÍA','17','18');
INSERT INTO AREA VALUES ('OTORRINOLARIONGOLOGÍA','18','9');
INSERT INTO AREA VALUES ('UROLOGÍA','19','6');
INSERT INTO AREA VALUES ('LABORATORIOS CLÍNICOS','20','16');
INSERT INTO AREA VALUES ('RADIODIAGNÓSTICO','21','18');
INSERT INTO AREA VALUES ('FARMACIA','22','9');
INSERT INTO AREA VALUES ('MEDICINA PREVENTIVA','23','17');
GO





INSERT INTO APLICANTES VALUES ('AROCAS PASADAS','africa@altecom.es','CALLE ROMA 371 - 375','32115858','5 Años','Universitario','MUCHAS','ESTEFANIA','957417772','ASCENDER','8151','Titulo Universitario','1','4','16');
INSERT INTO APLICANTES VALUES ('VISO GILABERT','agata@hotmail.com','AV. PASEO DE LA REPUBLICA 291 INT. 1803','47823588','5 Años','Universitario','MUCHAS','QUERALT','985594212','ASCENDER','7687','Titulo Universitario','2','6','7');
INSERT INTO APLICANTES VALUES ('AYALA FERRERAS','curie@minorisa.es','CALLE RAMON RIBEYRO 264 URB. SAN ANTONIO','10925766','12 Años','Universitario','MUCHAS','JOAN','989332112','ASCENDER','4342','Titulo Universitario','3','4','10');
INSERT INTO APLICANTES VALUES ('BAEZ TEJADO','albatros@wandoo.es','AV. SANTA CATALINA 529 - LA VICTORIA','39554565','14 Años','Universitario','MUCHAS','JOAN','982913271','ASCENDER','2294','Titulo Universitario','4','8','3');
INSERT INTO APLICANTES VALUES ('BASTARDES SOTO','albert@intercom.es','AV. SANTO TORIBIO 143 (6TO. PISO) EDIFICIO STO. TORIBIO','66651992','9 Años','Universitario','MUCHAS','MARC','953290587','ASCENDER','4706','Titulo Universitario','5','10','11');
INSERT INTO APLICANTES VALUES ('ANGUERA VILAFRANCA','alien@intercom.es','JR. CARABAYA 560 OF. 04 (2DO. PISO)','11581010','2 Años','Universitario','MUCHAS','JOSEP','948089237','ASCENDER','1351','Titulo Universitario','6','10','14');
INSERT INTO APLICANTES VALUES ('PASCUAL ALOY','amores@hotmail.com','JR. CARABAYA 560 OF. 04 (2DO. PISO)','48410763','5 Años','Universitario','MUCHAS','ESTHER','906895973','ASCENDER','7024','Titulo Universitario','7','3','6');
INSERT INTO APLICANTES VALUES ('VALLÉS GIRVENT','anabel@altecom.es','CALLE ALCALA 350 - URB. LA CASTELLANA (OVALO HIGUERETA)','44084400','12 Años','Universitario','MUCHAS','LAURA','989564627','ASCENDER','5581','Titulo Universitario','8','1','4');
INSERT INTO APLICANTES VALUES ('RAYA GARCIA','antiga@minorisa.es','AV. JAVIER PRADO OESTE 2361','34370353','12 Años','Universitario','MUCHAS','RAQUEL','916491387','ASCENDER','8881','Titulo Universitario','9','2','1');
INSERT INTO APLICANTES VALUES ('ANDREU CRUZ','ballador@hotmail.com','AV. RESIDENCIAL SALAVERRY BLOCK 1 DPTO 202','45416063','2 Años','Universitario','MUCHAS','JOAN','972123806','ASCENDER','8365','Titulo Universitario','10','3','11');
INSERT INTO APLICANTES VALUES ('BARALDÉS COMAS','balladora@altecom.es','CALLE ANTEQUERA 176 OF. 302','45527631','10 Años','Universitario','MUCHAS','MARIA','928963249','ASCENDER','7780','Titulo Universitario','11','1','7');
INSERT INTO APLICANTES VALUES ('BERENGUERAS CULLERÉS','barbilla@hotmail.com','URB. VILLA VICTORIA MZ.I - LT.8 (DEPARTAMENTO 301)','26666632','5 Años','Universitario','MUCHAS','ADRIÀ','954213306','ASCENDER','2601','Titulo Universitario','12','7','11');
INSERT INTO APLICANTES VALUES ('GARCIA UCEDA','besugo@minorisa.es','CALLE CORONEL ANDRES REYES NRO. 360 INT. 703 URB. JARDIN','41982570','4 Años','Universitario','MUCHAS','GERARD','985095638','ASCENDER','7355','Titulo Universitario','13','9','12');
INSERT INTO APLICANTES VALUES ('ARNAU MORENO','bogart@terra.es','CALLE PAZ SOLDAN 170 OF. 205','37345679','5 Años','Universitario','MUCHAS','ELIOT','936671680','ASCENDER','1513','Titulo Universitario','14','6','5');
INSERT INTO APLICANTES VALUES ('RAYA GAVILAN','bond@terra.es','CALLE PAZ SOLDAN 170 OF. 205','73939449','12 Años','Universitario','MUCHAS','JORDI','964513987','ASCENDER','1599','Titulo Universitario','15','8','16');
INSERT INTO APLICANTES VALUES ('ZAMBUDIO FIGULS','dalí@wandoo.es','AV. AV. IGNACIO MERINO NRO. 2422 INT. 101','48938133','8 Años','Universitario','MUCHAS','LLUÍS','906609997','ASCENDER','7396','Titulo Universitario','16','4','8');
INSERT INTO APLICANTES VALUES ('BIDAULT CULLERÉS','cela@altecom.es','AV. 28 DE JULIO NRO. 1044 DPTO. 601 URB. SAN ANTONIO','27889437','6 Años','Universitario','MUCHAS','LAURA','931268332','ASCENDER','9912','Titulo Universitario','17','6','16');
INSERT INTO APLICANTES VALUES ('BIOSCA FONTANET','coco@hotmail.com','CALLE MANUEL ALMENARA #265','21217945','14 Años','Universitario','MUCHAS','JORDI','964005079','ASCENDER','4884','Titulo Universitario','18','9','15');
INSERT INTO APLICANTES VALUES ('ZAFRA FIGULS','conejo@minorisa.es','AV. RESIDENCIAL SALAVERRY BLOCK 1 DPTO 202','42712351','7 Años','Universitario','MUCHAS','DOUNYA','920466216','ASCENDER','1398','Titulo Universitario','19','8','5');
INSERT INTO APLICANTES VALUES ('ALEU ICART','corcel@altecom.es','CALLE LAS CODORNICES 285','64673201','8 Años','Universitario','MUCHAS','JULIO','925439449','ASCENDER','8486','Titulo Universitario','20','5','4');
GO





INSERT INTO Requerimiento VALUES ('Tener mas de 18','1');
INSERT INTO Requerimiento VALUES ('Ser peruano','2');
INSERT INTO Requerimiento VALUES ('Ser soltero','3');
INSERT INTO Requerimiento VALUES ('Secundaria completa','4');
INSERT INTO Requerimiento VALUES ('No registrar antecedentes policiales, penales ni judiciales','5');
INSERT INTO Requerimiento VALUES ('Copia del Título de Médico','6');
GO





INSERT INTO AplicantesRequerimiento VALUES ('1','6');
INSERT INTO AplicantesRequerimiento VALUES ('2','6');
INSERT INTO AplicantesRequerimiento VALUES ('3','6');
INSERT INTO AplicantesRequerimiento VALUES ('4','6');
INSERT INTO AplicantesRequerimiento VALUES ('5','4');
INSERT INTO AplicantesRequerimiento VALUES ('6','5');
GO





INSERT INTO Rendimiento VALUES ('1','188','20','4','ME PARECE INJUSTO','1');
INSERT INTO Rendimiento VALUES ('1','206','19','5','NO OPINO','2');
INSERT INTO Rendimiento VALUES ('2','216','13','9','NO OPINO','3');
INSERT INTO Rendimiento VALUES ('0','192','19','9','NO OPINO','4');
INSERT INTO Rendimiento VALUES ('8','186','10','0','NO OPINO','5');
INSERT INTO Rendimiento VALUES ('5','190','13','1','ME PARECE MAL','6');
INSERT INTO Rendimiento VALUES ('5','199','16','6','NO OPINO','7');
INSERT INTO Rendimiento VALUES ('6','180','7','6','ME PARECE MAL','8');
INSERT INTO Rendimiento VALUES ('2','212','10','10','ME PARECE BIEN','9');
INSERT INTO Rendimiento VALUES ('7','247','6','3','ME PARECE INJUSTO','10');
INSERT INTO Rendimiento VALUES ('6','240','8','9','ME PARECE MAL','11');
INSERT INTO Rendimiento VALUES ('6','227','19','7','ME PARECE BIEN','12');
INSERT INTO Rendimiento VALUES ('1','208','8','8','ME PARECE INJUSTO','13');
INSERT INTO Rendimiento VALUES ('7','223','13','1','ME PARECE INJUSTO','14');
INSERT INTO Rendimiento VALUES ('0','241','9','8','ME PARECE BIEN','15');
INSERT INTO Rendimiento VALUES ('6','249','5','5','ME PARECE BIEN','16');
INSERT INTO Rendimiento VALUES ('2','229','7','6','ME PARECE MAL','17');
INSERT INTO Rendimiento VALUES ('3','193','15','0','ME PARECE MAL','18');
INSERT INTO Rendimiento VALUES ('8','238','13','3','ME PARECE BIEN','19');
INSERT INTO Rendimiento VALUES ('6','254','13','10','ME PARECE INJUSTO','20');
INSERT INTO Rendimiento VALUES ('5','249','11','3','ME PARECE MAL','21');
INSERT INTO Rendimiento VALUES ('4','227','16','8','ME PARECE MAL','22');
INSERT INTO Rendimiento VALUES ('9','247','8','8','ME PARECE INJUSTO','23');
INSERT INTO Rendimiento VALUES ('3','247','6','8','ME PARECE INJUSTO','24');
INSERT INTO Rendimiento VALUES ('6','194','14','5','NO OPINO','25');
INSERT INTO Rendimiento VALUES ('2','239','19','10','ME PARECE MAL','26');
INSERT INTO Rendimiento VALUES ('5','213','18','3','ME PARECE BIEN','27');
INSERT INTO Rendimiento VALUES ('3','196','12','10','ME PARECE MAL','28');
INSERT INTO Rendimiento VALUES ('7','204','6','7','ME PARECE MAL','29');
INSERT INTO Rendimiento VALUES ('9','199','17','3','NO OPINO','30');
INSERT INTO Rendimiento VALUES ('4','194','14','1','ME PARECE MAL','31');
INSERT INTO Rendimiento VALUES ('10','232','9','2','ME PARECE INJUSTO','32');
INSERT INTO Rendimiento VALUES ('2','217','5','8','ME PARECE INJUSTO','33');
INSERT INTO Rendimiento VALUES ('1','251','11','6','ME PARECE INJUSTO','34');
INSERT INTO Rendimiento VALUES ('7','249','19','5','ME PARECE INJUSTO','35');
INSERT INTO Rendimiento VALUES ('5','227','14','7','ME PARECE INJUSTO','36');
INSERT INTO Rendimiento VALUES ('5','233','7','2','ME PARECE BIEN','37');
INSERT INTO Rendimiento VALUES ('2','195','6','8','NO OPINO','38');
INSERT INTO Rendimiento VALUES ('2','211','8','1','ME PARECE MAL','39');
INSERT INTO Rendimiento VALUES ('3','182','7','4','NO OPINO','40');
INSERT INTO Rendimiento VALUES ('9','252','19','1','NO OPINO','41');
INSERT INTO Rendimiento VALUES ('2','184','20','3','ME PARECE MAL','42');
INSERT INTO Rendimiento VALUES ('1','229','13','10','ME PARECE BIEN','43');
INSERT INTO Rendimiento VALUES ('10','220','7','2','ME PARECE MAL','44');
INSERT INTO Rendimiento VALUES ('5','210','13','0','ME PARECE INJUSTO','45');
INSERT INTO Rendimiento VALUES ('1','187','7','1','ME PARECE MAL','46');
INSERT INTO Rendimiento VALUES ('8','256','16','0','ME PARECE BIEN','47');
INSERT INTO Rendimiento VALUES ('6','257','15','7','ME PARECE BIEN','48');
INSERT INTO Rendimiento VALUES ('2','257','18','8','ME PARECE BIEN','49');
INSERT INTO Rendimiento VALUES ('1','223','7','8','ME PARECE INJUSTO','50');
INSERT INTO Rendimiento VALUES ('9','227','12','5','ME PARECE INJUSTO','51');
INSERT INTO Rendimiento VALUES ('7','219','12','9','NO OPINO','52');
INSERT INTO Rendimiento VALUES ('3','208','12','0','ME PARECE BIEN','53');
INSERT INTO Rendimiento VALUES ('6','197','10','10','NO OPINO','54');
INSERT INTO Rendimiento VALUES ('7','201','15','3','ME PARECE INJUSTO','55');
INSERT INTO Rendimiento VALUES ('9','249','13','0','NO OPINO','56');
INSERT INTO Rendimiento VALUES ('5','260','11','2','ME PARECE MAL','57');
INSERT INTO Rendimiento VALUES ('4','227','17','6','NO OPINO','58');
INSERT INTO Rendimiento VALUES ('4','233','18','10','ME PARECE MAL','59');
INSERT INTO Rendimiento VALUES ('6','240','19','4','ME PARECE INJUSTO','60');
INSERT INTO Rendimiento VALUES ('2','198','6','3','NO OPINO','61');
INSERT INTO Rendimiento VALUES ('3','211','12','8','ME PARECE MAL','62');
INSERT INTO Rendimiento VALUES ('2','222','14','0','ME PARECE MAL','63');
INSERT INTO Rendimiento VALUES ('4','184','16','7','ME PARECE INJUSTO','64');
INSERT INTO Rendimiento VALUES ('10','201','5','9','ME PARECE INJUSTO','65');
INSERT INTO Rendimiento VALUES ('5','253','10','2','ME PARECE BIEN','66');
INSERT INTO Rendimiento VALUES ('8','191','6','1','ME PARECE MAL','67');
INSERT INTO Rendimiento VALUES ('5','203','19','7','ME PARECE MAL','68');
INSERT INTO Rendimiento VALUES ('0','208','13','5','NO OPINO','69');
INSERT INTO Rendimiento VALUES ('0','193','8','0','ME PARECE MAL','70');
INSERT INTO Rendimiento VALUES ('4','213','13','0','NO OPINO','71');
INSERT INTO Rendimiento VALUES ('10','215','14','2','NO OPINO','72');
INSERT INTO Rendimiento VALUES ('4','211','13','0','ME PARECE BIEN','73');
INSERT INTO Rendimiento VALUES ('1','254','9','5','NO OPINO','74');
INSERT INTO Rendimiento VALUES ('10','202','17','10','ME PARECE INJUSTO','75');
INSERT INTO Rendimiento VALUES ('3','198','8','7','NO OPINO','76');
INSERT INTO Rendimiento VALUES ('8','211','20','1','ME PARECE BIEN','77');
INSERT INTO Rendimiento VALUES ('7','180','10','8','ME PARECE INJUSTO','78');
INSERT INTO Rendimiento VALUES ('7','205','6','5','NO OPINO','79');
INSERT INTO Rendimiento VALUES ('4','229','18','8','ME PARECE BIEN','80');
INSERT INTO Rendimiento VALUES ('0','253','10','10','NO OPINO','81');
INSERT INTO Rendimiento VALUES ('10','189','14','6','ME PARECE MAL','82');
INSERT INTO Rendimiento VALUES ('5','248','12','3','ME PARECE BIEN','83');
INSERT INTO Rendimiento VALUES ('7','218','13','4','ME PARECE BIEN','84');
INSERT INTO Rendimiento VALUES ('7','206','5','9','ME PARECE MAL','85');
INSERT INTO Rendimiento VALUES ('6','234','15','5','NO OPINO','86');
INSERT INTO Rendimiento VALUES ('8','227','17','3','ME PARECE MAL','87');
INSERT INTO Rendimiento VALUES ('8','202','9','0','ME PARECE MAL','88');
INSERT INTO Rendimiento VALUES ('2','185','15','1','ME PARECE INJUSTO','89');
INSERT INTO Rendimiento VALUES ('4','206','15','10','ME PARECE MAL','90');
INSERT INTO Rendimiento VALUES ('0','183','6','2','ME PARECE INJUSTO','91');
INSERT INTO Rendimiento VALUES ('7','196','16','4','NO OPINO','92');
INSERT INTO Rendimiento VALUES ('5','238','16','5','ME PARECE BIEN','93');
INSERT INTO Rendimiento VALUES ('6','247','14','6','ME PARECE MAL','94');
INSERT INTO Rendimiento VALUES ('8','226','5','1','NO OPINO','95');
INSERT INTO Rendimiento VALUES ('4','189','16','9','ME PARECE INJUSTO','96');
INSERT INTO Rendimiento VALUES ('8','249','10','8','ME PARECE BIEN','97');
INSERT INTO Rendimiento VALUES ('7','226','14','2','NO OPINO','98');
INSERT INTO Rendimiento VALUES ('9','195','18','2','ME PARECE MAL','99');
INSERT INTO Rendimiento VALUES ('2','191','17','1','NO OPINO','100');
GO






INSERT INTO Empleado VALUES ('LOYOLA BOHORQUEZ','africa@altecom.es','Av. Gonzalo Ugás N° 29','98818242','KARLA','648061','6780','1710','1','15','1','8');
INSERT INTO Empleado VALUES ('DIAS MUÑOZ','agata@hotmail.com','Lt. 3 Mz. B-1, Urb. Parque Industrial','59977163','JOSE','541031','2492','7900','2','16','2','1');
INSERT INTO Empleado VALUES ('SIFUENTES CABANILLAS','albatros@wandoo.es','Av.Julian Arce Larreta Mz 27 L 27 Victor Raul Haya De La Tor','65372987','LUZ','742743','7858','1452','3','7','3','1');
INSERT INTO Empleado VALUES ('FIGUEROA JIMENEZ','maeillanes@hotmail.com','Av.San Pablo 123','58396686','LAYEVSKA','170755','3206','2895','4','5','4','5');
INSERT INTO Empleado VALUES ('DIAZ DIAZ','maeillanes@hotmail.com','Urb San Jose de California','13347607','JOYZI','116209','9250','6270','5','1','5','3');
INSERT INTO Empleado VALUES ('RODRIGUEZ MEDINA','osabarca@hotmail.com','Av Mansiche 345','37100481','GABRIELA','217949','7817','3412','6','15','6','5');
INSERT INTO Empleado VALUES ('SERNAQUE SILVA','jhonatan@corporation.ven','Av. Larco 1770, Trujillo 13001','58800684','JHONATAN','376053','3661','4946','7','13','7','6');
INSERT INTO Empleado VALUES ('MORALES GONZALES','Sb.nashxo.sk8@hotmail.com','Urb El Bosque 947','93792947','LUIS','355060','5761','2439','8','4','8','2');
INSERT INTO Empleado VALUES ('ALCANTARA PEREZ','fran.afull@live.cl','Urb La Noria 126','63609973','GABRIEL','898680','4384','5475','9','5','9','7');
INSERT INTO Empleado VALUES ('MERINO GUTIERRES','carlosaguileram@hotmail.com','Psj Monaco 187','53696159','NICOLAS','389708','7980','1302','10','18','10','1');
INSERT INTO Empleado VALUES ('CABALLERO DIAS','ikis_rojo@hotmail.com','A1 lote 01,, Sta. Teresa de Jesús, Distrito de Víctor Larco Herrera','57415937','EMILIA','677246','1119','3522','11','15','11','8');
INSERT INTO Empleado VALUES ('PINEDA RISCO','vizkala@hotmail.com','Av. Juan Pablo II, Trujillo 13011','39708445','SEBASTIAN','600341','1067','1316','12','8','12','5');
INSERT INTO Empleado VALUES ('CRUZ LAZARO','alexus3@hotmail.com','1N, Distrito de Víctor Larco Herrera 13009, Trujillo 13001','85043310','ANDREA','630110','2436','7100','13','18','13','7');
INSERT INTO Empleado VALUES ('GAVIDIA RISCO','capitanaguilera@hotmail.com','Las Capullanas 273, Distrito de Víctor Larco Herrera 13009','30428299','DANIELA','171486','9476','6157','14','1','14','3');
INSERT INTO Empleado VALUES ('RIOS GARCIA','apalamosg@hotmail.com','Av. Primavera 43, Distrito de Víctor Larco Herrera 13008','29865082','MATIAS','267676','6980','2031','15','5','15','10');
INSERT INTO Empleado VALUES ('AVILA MASJUAN','cangur@intercom.es','SECTOR 8 GRUPO 1 MZ. C LT. 12','38302611','Fuego','782330','9971','4952','16','5','16','5');
INSERT INTO Empleado VALUES ('PARRAMON FLORES','caparranas@altecom.es','CALLE LUIS GALVANI 234 URB. IND. SANTA ROSA','51909470','Galgo','614082','8814','7051','17','14','17','2');
INSERT INTO Empleado VALUES ('AGUILAR RAMOS','carretero@intercom.es','CALLE JOSE CARLOS MARIATEGUI MZA. G LOTE. 21 URB. URB. AEROPUERTO 2DO SECT','51762158','Garota','713229','5196','7930','18','3','18','10');
INSERT INTO Empleado VALUES ('AYALA ALSINA','cela@altecom.es','PLAZA BL. G NRO. 3 DPTO. 301 URB. MANZANILLA','26208657','gata','395450','7200','2711','19','12','19','1');
INSERT INTO Empleado VALUES ('ALVAREZ TROYANO','coco@hotmail.com','SECTOR 8 GRUPO 1 MZ. C LT. 12','57823365','Gateta','997987','7682','7754','20','17','20','9');
INSERT INTO Empleado VALUES ('ALINS GONZÁLEZ','conejo@minorisa.es','AV. JOAQUIN CAPELLO 366 DPTO 405 UIRB. SANTA CRUZ','11813409','Gioconda','227033','5961','1891','21','11','21','7');
INSERT INTO Empleado VALUES ('ACUÑA TORT','corcel@altecom.es','JR. FRANCIA Nº 1813 LA VICTORIA','21921135','Groucho','765380','8027','1266','22','18','22','1');
INSERT INTO Empleado VALUES ('ALGUÉ TRANCHO','curie@minorisa.es','AV. MARISCAL ELOY URETA 316 URB. EL PINO','53899286','Harpo','232493','8001','1481','23','3','23','2');
INSERT INTO Empleado VALUES ('BADIA CASTILLO','dalí@wandoo.es','JR. RIO TUMBES 215 URB. LAS MORAS','49751463','Hispa','969879','9518','6784','24','15','24','6');
INSERT INTO Empleado VALUES ('BENITEZ FLORES','dolça@cidet.com','CALLE ENRIQUE BARRON 280 URB.TEJADA','23921549','Hojalatero','189412','6332','7511','25','13','25','9');
INSERT INTO Empleado VALUES ('TORRUELLA GARCIA','dorada@intercom.es','AV. AV. JAVIER PRADO OESTE NRO. 2367 DPTO. 202','69041724','Huevo','496269','7453','6441','26','7','26','8');
INSERT INTO Empleado VALUES ('ALBERICH RODRIGUEZ','elisa@altecom.es','PSJE. SEÑOR DE LOS MILAGROS 103 MERCADO PRODUCTORES','32542085','James Dean','391785','2215','4837','27','13','27','10');
INSERT INTO Empleado VALUES ('ARMENCOT PUIG','encarna@hotmail.com','CALLE 54 NRO 109 INT. 205 URB. CORPAC','38516007','Jéssica','460190','5357','5057','28','5','28','6');
INSERT INTO Empleado VALUES ('ALIGUÉ RIVERA','entesa@altecom.es','PSJE. SEÑOR DE LOS MILAGROS 103 MERCADO PRODUCTORES','37382703','Julia','625296','5717','7039','29','4','29','9');
INSERT INTO Empleado VALUES ('BARRIGA RIU','et@altecom.es','MZ. O LT 11 SECTOR C3 PROYECTO.PILOTO PACHACUTEC','69214278','Julio','868047','1355','8922','30','10','30','7');
INSERT INTO Empleado VALUES ('PORTELLA GISPETS','experta@wandoo.es','JR. RIO TUMBES 215 URB. LAS MORAS','75740005','Lali','850381','1732','8672','31','15','31','5');
INSERT INTO Empleado VALUES ('AGUILERA BAENA','f5@wandoo.es','CALLE MANUEL UGARTECHE MZ Z 2 LT. 24 URB. GRUMETE MEDINA','52123967','libero','943265','1411','7858','32','11','32','7');
INSERT INTO Empleado VALUES ('RODRIGUEZ GARCÍA','fina@hotmail.com','AV. JAVIER PRADO ESTE 560 INT. 1502 (A LADO DE 566)','83444448','Llus','536358','8187','8065','33','11','33','2');
INSERT INTO Empleado VALUES ('AGUILAR SUNYÉ','fuego@altecom.es','AV. JAVIER PRADO ESTE 560 INT. 1502 (A LADO DE 566)','43008407','Loli','749723','2118','2704','34','13','34','4');
INSERT INTO Empleado VALUES ('BARRIGA TARDÀ','garota@hotmail.com','CALLE EL HABITO 921 - URB. CANTO GRANDE','49949279','Madonna','287508','4346','2340','35','14','35','7');
INSERT INTO Empleado VALUES ('BARCONS LARA','gateta@cataloniamail.com','JR. LAS PERLAS 1882 2DO PISO','17024741','Mata Hari','273806','4069','4470','36','13','36','6');
INSERT INTO Empleado VALUES ('AGUILERA TATJÉ','groucho@intercom.es','CALLE COMANDANTE JIMENEZ 150','85724937','Melanie','665830','7410','1165','37','13','37','10');
INSERT INTO Empleado VALUES ('ALEU PRAT','harpo@hotmail.com','AV. REYNALDO SAAVEDRA PINON 2627 URB. ELIO','44979597','Melquíades','446038','3655','2795','38','6','38','10');
INSERT INTO Empleado VALUES ('VALLÉS GIRVENT','hispa@cataloniamail.com','AV. MARISCAL ELOY URETA 316 URB. EL PINO','92646158','Merche','545819','4609','7125','39','15','39','3');
INSERT INTO Empleado VALUES ('MOLINA GARRIDO','huevo@terra.es','CALLE COMANDANTE JIMENEZ 150','44803578','Midas','565959','6134','8713','40','14','40','7');
INSERT INTO Empleado VALUES ('ARISSA HERMOSO','james dean@intercom.es','JR. FRANCIA Nº 1813 LA VICTORIA','35579889','Mona lisa','979974','2315','5389','41','11','41','3');
INSERT INTO Empleado VALUES ('BARALDÉS PARDO','jéssica@hotmail.com','CALLE COMANDANTE JIMENEZ 150','75037361','Moro','160861','3681','3661','42','10','42','2');
INSERT INTO Empleado VALUES ('SUAREZ GARZÓN','llus@hotmail.com','SECTOR 8 GRUPO 1 MZ. C LT. 12','79612312','Mozart','740704','7367','1587','43','3','43','6');
INSERT INTO Empleado VALUES ('ARPA MORENO','madonna@wandoo.es','CALLE EL HABITO 921 - URB. CANTO GRANDE','69381238','Nadadora','274741','6389','1480','44','17','44','2');
INSERT INTO Empleado VALUES ('ALOY FARRANDO','mata hari@intercom.es','CALLE COMANDANTE JIMENEZ 150','90452257','Nalga','207777','3086','3086','45','16','45','1');
INSERT INTO Empleado VALUES ('LUQUE GARRIGASAIT','melanie@minorisa.es','JR. FRANCIA Nº 1813 LA VICTORIA','53935300','Napoleon','967207','4770','6696','46','14','46','4');
INSERT INTO Empleado VALUES ('RIDÓ GÓMEZ','melquíades@hotmail.com','JR. JR. BELAUNDE OESTE 198 URB. HUAQUILLAY','81986748','Orondo','296818','2934','6724','47','16','47','4');
INSERT INTO Empleado VALUES ('SANTAMARIA FLOTATS','merche@terra.es','JR. RIO TUMBES 215 URB. LAS MORAS','78672848','Papagayo','332315','1063','4027','48','16','48','4');
INSERT INTO Empleado VALUES ('HERMS GÓMEZ','midas@cataloniamail.com','CALLE COMANDANTE JIMENEZ 150','22364123','Paseante','968360','5908','6524','49','4','49','8');
INSERT INTO Empleado VALUES ('ARTIGAS MATURANO','mona lisa@minorisa.es','JR. RIO TUMBES 215 URB. LAS MORAS','47895454','Pasión','513403','8268','8170','50','12','50','2');
INSERT INTO Empleado VALUES ('AGUILAR MASANA','moro@minorisa.es','CALLE SEBASTIAN SALAZAR BONDY NRO. 151 URB. JACARANDA MAGDALENA DEL MAR','21270118','Pato','525543','3865','5396','51','14','51','3');
INSERT INTO Empleado VALUES ('ALTIMIRAS SERAROLS','mozart@wandoo.es','AV. JOSE PARDO 434 DPTO. 405','95977966','Pelusa','587683','6535','2007','52','2','52','10');
INSERT INTO Empleado VALUES ('TORRESCASANA GARCIA','napoleon@cidet.com','CALLE PALCA NRO. 172 INT. 201 (EDIFICIO CHINCHA 2DO PISO) LIMA - LIMA - LIMA','81961687','Perla','967217','1250','7571','53','17','53','10');
INSERT INTO Empleado VALUES ('ARIZA PUIGBÓ','orondo@altecom.es','AV. SAN BORJA NORTE 421 DPTO 201','42858224','Picasso','547900','6863','4444','54','6','54','10');
INSERT INTO Empleado VALUES ('ALVAREZ ARMENTEROS','papagayo@altecom.es','CALLE ROMA 371 - 375','14261866','poma','901718','6182','7171','55','1','55','3');
INSERT INTO Empleado VALUES ('BARALDÉS TARRAGÓ','pasión@altecom.es','AV. PASEO DE LA REPUBLICA 291 INT. 1803','71310625','Psicosis','536077','9485','2075','56','14','56','5');
INSERT INTO Empleado VALUES ('GARCIA GARCÍA','pelusa@hotmail.com','CALLE RAMON RIBEYRO 264 URB. SAN ANTONIO','36442204','Quince centimos','628082','8648','6336','57','3','57','8');
INSERT INTO Empleado VALUES ('AROCA GÓMEZ','perla@cataloniamail.com','AV. SANTA CATALINA 529 - LA VICTORIA','82199893','Rebeca','256981','3086','4796','58','2','58','8');
INSERT INTO Empleado VALUES ('ALONSO RODRIGUEZ','psicosis@intercom.es','AV. SANTO TORIBIO 143 (6TO. PISO) EDIFICIO STO. TORIBIO','72851163','Rebelde','192560','8710','6779','59','13','59','5');
INSERT INTO Empleado VALUES ('CANO GÓMEZ','rebeca@cataloniamail.com','JR. CARABAYA 560 OF. 04 (2DO. PISO)','10019055','Recio','302237','4763','8902','60','11','60','5');
INSERT INTO Empleado VALUES ('ALCAIDE MOLINA','rebelde@intercom.es','JR. CARABAYA 560 OF. 04 (2DO. PISO)','79667261','Recital','993393','5273','2577','61','16','61','8');
INSERT INTO Empleado VALUES ('AGUILERA PRAT','rene@intercom.es','CALLE ALCALA 350 - URB. LA CASTELLANA (OVALO HIGUERETA)','19008020','Rene','894786','8658','4847','62','12','62','5');
INSERT INTO Empleado VALUES ('ALAPONT ICART','rica@terra.es','AV. JAVIER PRADO OESTE 2361','86932058','Repicó','394083','9407','7876','63','18','63','2');
INSERT INTO Empleado VALUES ('RIVERO FLORIDO','rockera@terra.es','AV. RESIDENCIAL SALAVERRY BLOCK 1 DPTO 202','90995123','Rica','401184','2904','3606','64','1','64','1');
INSERT INTO Empleado VALUES ('AVILA MASJUAN','roman@wandoo.es','CALLE ANTEQUERA 176 OF. 302','81696634','Rockera','485455','6730','8790','65','13','65','1');
INSERT INTO Empleado VALUES ('GRANADOS ANDRÉS','romeo@intercom.es','URB. VILLA VICTORIA MZ.I - LT.8 (DEPARTAMENTO 301)','93294652','Roma','761379','3567','5710','66','18','66','10');
INSERT INTO Empleado VALUES ('FERRER GASSET','ronc@cataloniamail.com','CALLE CORONEL ANDRES REYES NRO. 360 INT. 703 URB. JARDIN','38077260','Roman','831293','5570','7247','67','12','67','5');
INSERT INTO Empleado VALUES ('AMIGO MODREGO','sabrosa@hotmail.com','CALLE PAZ SOLDAN 170 OF. 205','34685990','Romario','417745','9251','4822','68','17','68','7');
INSERT INTO Empleado VALUES ('ABDIN TATJÈ','salsa@cataloniamail.com','CALLE PAZ SOLDAN 170 OF. 205','44475529','Romeo','465072','7939','4244','69','16','69','9');
INSERT INTO Empleado VALUES ('CANELLAS GOMEZ','sincer@altecom.es','AV. AV. IGNACIO MERINO NRO. 2422 INT. 101','81221571','Romesco','557895','1109','2632','70','9','70','7');
INSERT INTO Empleado VALUES ('HIDALGO ALTIMIRAS','sincera@hotmail.com','AV. 28 DE JULIO NRO. 1044 DPTO. 601 URB. SAN ANTONIO','89017109','RONC','467410','2957','8015','71','3','71','7');
INSERT INTO Empleado VALUES ('BASTARDAS FRANCH','suau@hotmail.com','CALLE MANUEL ALMENARA #265','38056693','Sabrosa','965052','1294','4751','72','3','72','6');
INSERT INTO Empleado VALUES ('ABADIAS MASANA','superman@altecom.es','AV. RESIDENCIAL SALAVERRY BLOCK 1 DPTO 202','26908700','Salsa','145437','8089','7712','73','4','73','4');
INSERT INTO Empleado VALUES ('AREVALO SANCHEZ','superwoman@wandoo.es','CALLE LAS CODORNICES 285','73729412','sandra','342188','7596','8920','74','7','74','7');
INSERT INTO Empleado VALUES ('ALINS MULET','tablon@hotmail.com','AV. PARQUE NORTE 1160 OFC. 402 - RES. CENTRO EMP PARQUE NORTE','67435915','Sha','803517','3334','5205','75','6','75','3');
INSERT INTO Empleado VALUES ('GARCIA GONZÁLEZ','tendre@terra.es','JR. JORGE CHAVEZ 150','34608206','Sincer','282610','3110','2741','76','12','76','6');
INSERT INTO Empleado VALUES ('ALVAREZ PARCERISA','teta@intercom.es','AV. PEDRO DE OSMA 402','68025169','Sincera','843809','7892','6893','77','11','77','6');
INSERT INTO Empleado VALUES ('CASAS ANDRÉS','tomasa@hotmail.com','AV. PABLO BERMUDEZ NRO. 254 E','22958053','suau','370127','4809','6495','78','1','78','2');
INSERT INTO Empleado VALUES ('MORALES GESE','tremenda@altecom.es','CALLE DEAN VALDIVIA 148 PISO 11 OF. REGUS','66531465','Superman','581698','1085','7263','79','15','79','5');
INSERT INTO Empleado VALUES ('BARALDÉS MARTORELL','tripa@intercom.es','AV. 28 DE JULIO NRO. 1044 DPTO. 601 URB. SAN ANTONIO','72538410','Superwoman','556045','6478','7146','80','2','80','7');
INSERT INTO Empleado VALUES ('AROCA GÓMEZ','verruga@hotmail.com','PSJE. SUCRE 177','29628114','Tablon','549251','2979','4125','81','10','81','9');
INSERT INTO Empleado VALUES ('RUEDA ALVAREZ','ronc@cataloniamail.com','AV. TOMAS MARSANO 1790 DPTO. 201','46799706','tendre','370952','7279','5592','82','14','82','4');
INSERT INTO Empleado VALUES ('ALVAREZ DOMENECH','sabrosa@hotmail.com','CALLE ARCE #139 DPTO 604','71307092','Teta','389447','4635','4362','83','2','83','10');
INSERT INTO Empleado VALUES ('BOIX GONZÁLEZ','salsa@cataloniamail.com','AV. JAVIER PADO OESTE 203','19243601','Tomasa','946986','8310','1941','84','13','84','10');
INSERT INTO Empleado VALUES ('BARALDÉS MONRÓS','sincer@altecom.es','CALLE INDEPENDENCIA 663 URB. MIRAFLORES','61872353','Tranquil','508516','2040','1556','85','10','85','7');
INSERT INTO Empleado VALUES ('AGUILERA MERINO','sincera@hotmail.com','CALLE JOSE TORIBIO POLO 327 INT 709 URB. SANTA CRUZ','33343543','Tremenda','595035','4883','8957','86','6','86','4');
INSERT INTO Empleado VALUES ('BAREA DHAENE','suau@hotmail.com','AV. SALAVERRY 674 DPTO. 501','53466372','Tripa','504953','7885','2429','87','1','87','4');
INSERT INTO Empleado VALUES ('BARROSO DHAENE','tablon@hotmail.com','AV. JAVIER PRADO ESTE 560 OFC 2302 , PISO 23','91827082','Verruga','288611','3704','3157','88','16','88','8');
GO





INSERT INTO Asistencia VALUES ('ASISTIO','16/08/2020','1','67');
INSERT INTO Asistencia VALUES ('ASISTIO','13/02/2020','2','18');
INSERT INTO Asistencia VALUES ('ASISTIO','3/05/2020','3','45');
INSERT INTO Asistencia VALUES ('ASISTIO','20/11/2020','4','52');
INSERT INTO Asistencia VALUES ('ASISTIO','20/05/2021','5','59');
INSERT INTO Asistencia VALUES ('ASISTIO','24/07/2020','6','24');
INSERT INTO Asistencia VALUES ('ASISTIO','29/03/2020','7','13');
INSERT INTO Asistencia VALUES ('ASISTIO','2/02/2020','8','42');
INSERT INTO Asistencia VALUES ('ASISTIO','7/09/2020','9','81');
INSERT INTO Asistencia VALUES ('ASISTIO','15/11/2020','10','27');
INSERT INTO Asistencia VALUES ('ASISTIO','13/08/2021','11','61');
INSERT INTO Asistencia VALUES ('ASISTIO','14/04/2020','12','1');
INSERT INTO Asistencia VALUES ('ASISTIO','24/08/2020','13','74');
INSERT INTO Asistencia VALUES ('ASISTIO','3/04/2021','14','1');
INSERT INTO Asistencia VALUES ('ASISTIO','26/06/2020','15','80');
INSERT INTO Asistencia VALUES ('ASISTIO','15/10/2021','16','77');
INSERT INTO Asistencia VALUES ('ASISTIO','1/03/2021','17','48');
INSERT INTO Asistencia VALUES ('ASISTIO','1/05/2020','18','57');
INSERT INTO Asistencia VALUES ('ASISTIO','22/05/2020','19','62');
INSERT INTO Asistencia VALUES ('ASISTIO','4/03/2020','20','68');
INSERT INTO Asistencia VALUES ('ASISTIO','10/04/2020','21','11');
INSERT INTO Asistencia VALUES ('ASISTIO','13/09/2020','22','68');
INSERT INTO Asistencia VALUES ('ASISTIO','4/05/2021','23','34');
INSERT INTO Asistencia VALUES ('ASISTIO','2/07/2021','24','62');
INSERT INTO Asistencia VALUES ('ASISTIO','8/10/2021','25','78');
INSERT INTO Asistencia VALUES ('ASISTIO','8/07/2021','26','43');
INSERT INTO Asistencia VALUES ('ASISTIO','25/01/2021','27','24');
INSERT INTO Asistencia VALUES ('ASISTIO','23/03/2021','28','60');
INSERT INTO Asistencia VALUES ('ASISTIO','30/03/2020','29','83');
INSERT INTO Asistencia VALUES ('ASISTIO','2/04/2020','30','38');
INSERT INTO Asistencia VALUES ('ASISTIO','3/05/2020','31','71');
INSERT INTO Asistencia VALUES ('ASISTIO','30/07/2021','32','29');
INSERT INTO Asistencia VALUES ('ASISTIO','30/05/2020','33','80');
INSERT INTO Asistencia VALUES ('ASISTIO','2/04/2020','34','29');
INSERT INTO Asistencia VALUES ('ASISTIO','16/06/2020','35','66');
INSERT INTO Asistencia VALUES ('ASISTIO','10/05/2020','36','26');
INSERT INTO Asistencia VALUES ('ASISTIO','24/12/2021','37','2');
INSERT INTO Asistencia VALUES ('ASISTIO','19/08/2021','38','87');
INSERT INTO Asistencia VALUES ('ASISTIO','9/06/2020','39','72');
INSERT INTO Asistencia VALUES ('ASISTIO','10/05/2020','40','3');
INSERT INTO Asistencia VALUES ('ASISTIO','18/12/2020','41','11');
INSERT INTO Asistencia VALUES ('ASISTIO','7/12/2021','42','45');
INSERT INTO Asistencia VALUES ('ASISTIO','10/03/2021','43','82');
INSERT INTO Asistencia VALUES ('ASISTIO','7/09/2021','44','54');
INSERT INTO Asistencia VALUES ('ASISTIO','8/04/2021','45','9');
INSERT INTO Asistencia VALUES ('ASISTIO','10/05/2020','46','80');
INSERT INTO Asistencia VALUES ('ASISTIO','11/01/2021','47','69');
INSERT INTO Asistencia VALUES ('ASISTIO','26/09/2020','48','20');
INSERT INTO Asistencia VALUES ('ASISTIO','7/12/2021','49','6');
INSERT INTO Asistencia VALUES ('ASISTIO','10/01/2021','50','48');
INSERT INTO Asistencia VALUES ('ASISTIO','19/12/2020','51','35');
INSERT INTO Asistencia VALUES ('ASISTIO','6/08/2021','52','81');
INSERT INTO Asistencia VALUES ('ASISTIO','22/05/2021','53','52');
INSERT INTO Asistencia VALUES ('ASISTIO','29/10/2020','54','77');
INSERT INTO Asistencia VALUES ('ASISTIO','23/04/2020','55','58');
INSERT INTO Asistencia VALUES ('ASISTIO','25/12/2020','56','28');
INSERT INTO Asistencia VALUES ('ASISTIO','15/11/2021','57','86');
INSERT INTO Asistencia VALUES ('ASISTIO','8/04/2020','58','75');
INSERT INTO Asistencia VALUES ('ASISTIO','12/07/2020','59','49');
INSERT INTO Asistencia VALUES ('ASISTIO','12/08/2021','60','76');
INSERT INTO Asistencia VALUES ('ASISTIO','2/08/2021','61','79');
INSERT INTO Asistencia VALUES ('ASISTIO','18/05/2021','62','66');
INSERT INTO Asistencia VALUES ('ASISTIO','1/03/2020','63','20');
INSERT INTO Asistencia VALUES ('ASISTIO','26/06/2021','64','70');
INSERT INTO Asistencia VALUES ('ASISTIO','19/01/2020','65','76');
INSERT INTO Asistencia VALUES ('ASISTIO','7/04/2021','66','58');
INSERT INTO Asistencia VALUES ('ASISTIO','1/01/2020','67','32');
INSERT INTO Asistencia VALUES ('ASISTIO','4/12/2020','68','43');
INSERT INTO Asistencia VALUES ('ASISTIO','17/10/2021','69','55');
INSERT INTO Asistencia VALUES ('ASISTIO','25/03/2021','70','38');
INSERT INTO Asistencia VALUES ('ASISTIO','26/01/2021','71','11');
INSERT INTO Asistencia VALUES ('ASISTIO','22/08/2021','72','64');
INSERT INTO Asistencia VALUES ('ASISTIO','7/04/2021','73','15');
INSERT INTO Asistencia VALUES ('ASISTIO','17/03/2020','74','62');
INSERT INTO Asistencia VALUES ('ASISTIO','4/06/2020','75','49');
INSERT INTO Asistencia VALUES ('ASISTIO','1/03/2020','76','61');
INSERT INTO Asistencia VALUES ('ASISTIO','6/07/2021','77','45');
INSERT INTO Asistencia VALUES ('ASISTIO','19/08/2020','78','60');
INSERT INTO Asistencia VALUES ('ASISTIO','20/08/2021','79','79');
INSERT INTO Asistencia VALUES ('ASISTIO','12/10/2021','80','73');
INSERT INTO Asistencia VALUES ('ASISTIO','12/10/2021','81','42');
INSERT INTO Asistencia VALUES ('ASISTIO','19/03/2021','82','51');
INSERT INTO Asistencia VALUES ('ASISTIO','6/04/2020','83','21');
INSERT INTO Asistencia VALUES ('ASISTIO','24/06/2020','84','70');
INSERT INTO Asistencia VALUES ('ASISTIO','11/03/2020','85','22');
INSERT INTO Asistencia VALUES ('ASISTIO','16/12/2021','86','56');
INSERT INTO Asistencia VALUES ('ASISTIO','21/05/2020','87','25');
INSERT INTO Asistencia VALUES ('ASISTIO','3/04/2020','88','43');
INSERT INTO Asistencia VALUES ('ASISTIO','14/10/2020','89','76');
INSERT INTO Asistencia VALUES ('ASISTIO','14/06/2020','90','33');
INSERT INTO Asistencia VALUES ('ASISTIO','3/01/2021','91','62');
INSERT INTO Asistencia VALUES ('ASISTIO','26/08/2021','92','59');
INSERT INTO Asistencia VALUES ('ASISTIO','15/01/2021','93','60');
INSERT INTO Asistencia VALUES ('ASISTIO','25/12/2020','94','72');
INSERT INTO Asistencia VALUES ('ASISTIO','3/06/2020','95','15');
INSERT INTO Asistencia VALUES ('ASISTIO','1/02/2021','96','40');
INSERT INTO Asistencia VALUES ('ASISTIO','18/07/2021','97','33');
INSERT INTO Asistencia VALUES ('ASISTIO','4/06/2021','98','18');
INSERT INTO Asistencia VALUES ('ASISTIO','16/01/2021','99','61');
INSERT INTO Asistencia VALUES ('ASISTIO','8/03/2020','100','37');
INSERT INTO Asistencia VALUES ('ASISTIO','29/09/2020','101','63');
INSERT INTO Asistencia VALUES ('ASISTIO','28/06/2021','102','68');
INSERT INTO Asistencia VALUES ('ASISTIO','26/07/2020','103','55');
INSERT INTO Asistencia VALUES ('ASISTIO','8/01/2020','104','56');
INSERT INTO Asistencia VALUES ('ASISTIO','19/07/2020','105','29');
INSERT INTO Asistencia VALUES ('ASISTIO','17/08/2021','106','72');
INSERT INTO Asistencia VALUES ('ASISTIO','22/03/2021','107','42');
INSERT INTO Asistencia VALUES ('ASISTIO','7/06/2020','108','22');
INSERT INTO Asistencia VALUES ('ASISTIO','8/11/2020','109','3');
INSERT INTO Asistencia VALUES ('ASISTIO','13/02/2020','110','70');
INSERT INTO Asistencia VALUES ('ASISTIO','19/03/2020','111','85');
INSERT INTO Asistencia VALUES ('ASISTIO','14/04/2020','112','10');
INSERT INTO Asistencia VALUES ('ASISTIO','26/06/2020','113','86');
INSERT INTO Asistencia VALUES ('ASISTIO','13/10/2021','114','43');
INSERT INTO Asistencia VALUES ('ASISTIO','26/03/2020','115','11');
INSERT INTO Asistencia VALUES ('ASISTIO','29/11/2021','116','27');
INSERT INTO Asistencia VALUES ('ASISTIO','23/09/2021','117','23');
INSERT INTO Asistencia VALUES ('ASISTIO','12/06/2021','118','27');
INSERT INTO Asistencia VALUES ('ASISTIO','22/02/2021','119','29');
INSERT INTO Asistencia VALUES ('ASISTIO','21/07/2021','120','78');
INSERT INTO Asistencia VALUES ('ASISTIO','18/10/2021','121','27');
INSERT INTO Asistencia VALUES ('ASISTIO','29/07/2020','122','72');
INSERT INTO Asistencia VALUES ('ASISTIO','7/07/2020','123','80');
INSERT INTO Asistencia VALUES ('ASISTIO','5/02/2021','124','13');
INSERT INTO Asistencia VALUES ('ASISTIO','11/07/2020','125','24');
INSERT INTO Asistencia VALUES ('ASISTIO','18/04/2020','126','29');
INSERT INTO Asistencia VALUES ('ASISTIO','18/02/2020','127','59');
INSERT INTO Asistencia VALUES ('ASISTIO','1/07/2020','128','3');
INSERT INTO Asistencia VALUES ('ASISTIO','1/07/2021','129','27');
INSERT INTO Asistencia VALUES ('ASISTIO','29/08/2021','130','64');
INSERT INTO Asistencia VALUES ('ASISTIO','20/12/2020','131','25');
INSERT INTO Asistencia VALUES ('ASISTIO','15/07/2021','132','77');
INSERT INTO Asistencia VALUES ('ASISTIO','19/12/2020','133','21');
INSERT INTO Asistencia VALUES ('ASISTIO','28/09/2020','134','41');
INSERT INTO Asistencia VALUES ('ASISTIO','17/12/2020','135','46');
INSERT INTO Asistencia VALUES ('ASISTIO','20/07/2021','136','66');
INSERT INTO Asistencia VALUES ('ASISTIO','20/06/2021','137','34');
INSERT INTO Asistencia VALUES ('ASISTIO','30/05/2020','138','26');
INSERT INTO Asistencia VALUES ('ASISTIO','10/10/2020','139','80');
INSERT INTO Asistencia VALUES ('ASISTIO','1/07/2021','140','7');
INSERT INTO Asistencia VALUES ('ASISTIO','4/12/2021','141','30');
INSERT INTO Asistencia VALUES ('ASISTIO','24/05/2021','142','54');
INSERT INTO Asistencia VALUES ('ASISTIO','29/11/2021','143','61');
INSERT INTO Asistencia VALUES ('ASISTIO','29/05/2021','144','16');
INSERT INTO Asistencia VALUES ('ASISTIO','10/10/2021','145','77');
INSERT INTO Asistencia VALUES ('ASISTIO','13/12/2021','146','1');
INSERT INTO Asistencia VALUES ('ASISTIO','2/04/2021','147','26');
INSERT INTO Asistencia VALUES ('ASISTIO','24/03/2020','148','17');
INSERT INTO Asistencia VALUES ('ASISTIO','17/04/2020','149','5');
INSERT INTO Asistencia VALUES ('ASISTIO','18/04/2021','150','1');
INSERT INTO Asistencia VALUES ('ASISTIO','3/05/2020','151','33');
INSERT INTO Asistencia VALUES ('ASISTIO','6/05/2020','152','13');
INSERT INTO Asistencia VALUES ('ASISTIO','23/11/2021','153','34');
INSERT INTO Asistencia VALUES ('ASISTIO','9/11/2021','154','10');
INSERT INTO Asistencia VALUES ('ASISTIO','14/10/2020','155','24');
INSERT INTO Asistencia VALUES ('ASISTIO','12/09/2020','156','66');
INSERT INTO Asistencia VALUES ('ASISTIO','11/10/2021','157','16');
INSERT INTO Asistencia VALUES ('ASISTIO','28/10/2020','158','42');
INSERT INTO Asistencia VALUES ('ASISTIO','19/04/2020','159','4');
INSERT INTO Asistencia VALUES ('ASISTIO','16/02/2020','160','49');
INSERT INTO Asistencia VALUES ('ASISTIO','25/01/2021','161','53');
INSERT INTO Asistencia VALUES ('ASISTIO','17/07/2020','162','45');
INSERT INTO Asistencia VALUES ('ASISTIO','10/10/2021','163','26');
INSERT INTO Asistencia VALUES ('ASISTIO','6/05/2020','164','4');
INSERT INTO Asistencia VALUES ('ASISTIO','14/08/2021','165','28');
INSERT INTO Asistencia VALUES ('ASISTIO','5/11/2020','166','9');
INSERT INTO Asistencia VALUES ('ASISTIO','2/03/2021','167','9');
INSERT INTO Asistencia VALUES ('ASISTIO','27/04/2021','168','30');
INSERT INTO Asistencia VALUES ('ASISTIO','7/07/2020','169','43');
INSERT INTO Asistencia VALUES ('ASISTIO','7/11/2021','170','82');
INSERT INTO Asistencia VALUES ('ASISTIO','27/03/2021','171','35');
INSERT INTO Asistencia VALUES ('ASISTIO','26/06/2020','172','4');
INSERT INTO Asistencia VALUES ('ASISTIO','3/04/2020','173','56');
INSERT INTO Asistencia VALUES ('ASISTIO','21/02/2020','174','15');
INSERT INTO Asistencia VALUES ('ASISTIO','9/08/2021','175','26');
INSERT INTO Asistencia VALUES ('ASISTIO','30/05/2021','176','52');
INSERT INTO Asistencia VALUES ('ASISTIO','30/07/2021','177','74');
INSERT INTO Asistencia VALUES ('ASISTIO','1/01/2021','178','60');
INSERT INTO Asistencia VALUES ('ASISTIO','10/02/2021','179','56');
INSERT INTO Asistencia VALUES ('ASISTIO','4/12/2020','180','46');
INSERT INTO Asistencia VALUES ('ASISTIO','29/02/2020','181','14');
INSERT INTO Asistencia VALUES ('ASISTIO','29/10/2020','182','32');
INSERT INTO Asistencia VALUES ('ASISTIO','9/03/2021','183','64');
INSERT INTO Asistencia VALUES ('ASISTIO','5/10/2021','184','50');
INSERT INTO Asistencia VALUES ('ASISTIO','5/04/2021','185','69');
INSERT INTO Asistencia VALUES ('ASISTIO','26/08/2020','186','18');
INSERT INTO Asistencia VALUES ('ASISTIO','15/11/2021','187','41');
INSERT INTO Asistencia VALUES ('ASISTIO','6/09/2020','188','72');
INSERT INTO Asistencia VALUES ('ASISTIO','23/12/2021','189','12');
INSERT INTO Asistencia VALUES ('ASISTIO','6/10/2021','190','72');
INSERT INTO Asistencia VALUES ('ASISTIO','27/11/2020','191','88');
INSERT INTO Asistencia VALUES ('ASISTIO','19/07/2020','192','77');
INSERT INTO Asistencia VALUES ('ASISTIO','20/10/2020','193','19');
INSERT INTO Asistencia VALUES ('ASISTIO','12/02/2020','194','20');
INSERT INTO Asistencia VALUES ('ASISTIO','12/02/2021','195','16');
INSERT INTO Asistencia VALUES ('ASISTIO','20/09/2021','196','60');
INSERT INTO Asistencia VALUES ('ASISTIO','10/02/2020','197','40');
INSERT INTO Asistencia VALUES ('ASISTIO','16/08/2020','198','50');
INSERT INTO Asistencia VALUES ('ASISTIO','4/12/2020','199','7');
INSERT INTO Asistencia VALUES ('ASISTIO','15/05/2021','200','84');
GO



select



INSERT INTO Observacion VALUES ('TARDANZAS','20/10/2020','1','43');
INSERT INTO Observacion VALUES ('TARDANZAS','16/01/2021','2','78');
INSERT INTO Observacion VALUES ('TARDANZAS','3/02/2020','3','9');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','17/06/2021','4','86');
INSERT INTO Observacion VALUES ('TARDANZAS','25/03/2020','5','12');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','26/01/2020','6','65');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','7/04/2020','7','81');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','9/12/2021','8','76');
INSERT INTO Observacion VALUES ('TARDANZAS','12/02/2020','9','80');
INSERT INTO Observacion VALUES ('TARDANZAS','22/11/2020','10','49');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','19/05/2021','11','55');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','12/01/2020','12','67');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','26/01/2021','13','41');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','10/09/2021','14','17');
INSERT INTO Observacion VALUES ('TARDANZAS','15/05/2021','15','26');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','26/12/2020','16','39');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','14/03/2020','17','54');
INSERT INTO Observacion VALUES ('TARDANZAS','13/11/2020','18','58');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','12/07/2021','19','69');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','19/06/2021','20','20');
INSERT INTO Observacion VALUES ('TARDANZAS','22/03/2021','21','52');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','6/06/2020','22','28');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','9/12/2020','23','65');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','24/08/2021','24','18');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','12/12/2020','25','15');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','9/12/2020','26','6');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','18/03/2020','27','22');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','17/08/2020','28','1');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','24/07/2021','29','67');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','3/10/2021','30','67');
INSERT INTO Observacion VALUES ('TARDANZAS','19/05/2020','31','20');
INSERT INTO Observacion VALUES ('TARDANZAS','8/04/2020','32','2');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','28/11/2021','33','46');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','22/09/2021','34','48');
INSERT INTO Observacion VALUES ('TARDANZAS','3/10/2021','35','3');
INSERT INTO Observacion VALUES ('TARDANZAS','13/02/2021','36','10');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','26/06/2021','37','62');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','13/02/2021','38','46');
INSERT INTO Observacion VALUES ('TARDANZAS','30/04/2020','39','27');
INSERT INTO Observacion VALUES ('TARDANZAS','3/11/2021','40','13');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','27/08/2021','41','33');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','10/12/2021','42','29');
INSERT INTO Observacion VALUES ('TARDANZAS','6/10/2020','43','12');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','24/07/2021','44','24');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','3/08/2021','45','5');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','27/06/2021','46','29');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','17/09/2021','47','38');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','11/07/2021','48','52');
INSERT INTO Observacion VALUES ('INCUMPLIMIENTO DE LABORES','2/09/2020','49','14');
INSERT INTO Observacion VALUES ('FALTA DE RESPETO','17/04/2021','50','15');
GO

INSERT INTO Evaluación (EvaluaciónID,AplicantesID,Fechaevaluacion,Pregunta1,Pregunta2,Pregunta3,Pregunta4,Pregunta5,Puntajetotal) VALUES ('1','1','2/08/1997','4','0','0','0','0','4');
Go




--numero de asistencias
select COUNT(*) from Asistencia where EmpleadoID =80


---sueldo descontado
select Sueldo-((select cant_faltas from Rendimiento where RendimientoID =(select RendimientoID from Empleado where EmpleadoID =80))*30)from Empleado where EmpleadoID =80



SELECT EvaluaciónID,AplicantesID,Fechaevaluacion,Pregunta1,Pregunta2,Pregunta3,Pregunta4,Pregunta5,Puntajetotal FROM Evaluación



SELECT TOP 1 EvaluaciónID FROM Evaluación ORDER BY EvaluaciónID DESC 

SELECT * FROM Evaluación

SELECT TOP 1 RendimientoID FROM Rendimiento ORDER BY RendimientoID DESC 

SELECT * FROM Empleado